service: aws-serverless-python-apigateway
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'
provider:
 name: aws
 runtime: python3.8
 stage: dev
 region: us-east-1
 memorySize: 128

custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: 'ANY /{proxy+}'

plugins:
 - serverless-wsgi
 - serverless-python-requirements